# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/embedding/v1/embedding.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/embedding/v1/embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/embedding/v1/embedding.proto\x12\x0c\x65mbedding.v1\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"^\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x12\n\ndimensions\x18\x02 \x01(\x05\x12\x17\n\x0f\x62\x61se_dimensions\x18\x03 \x01(\x05\x12\r\n\x05model\x18\x04 \x01(\t2T\n\x10\x45mbeddingService\x12@\n\x05\x45mbed\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponseBXZVgithub.com/IanStuardo-Dev/backend-crud/internal/infrastructure/embedding/grpcpb;grpcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.embedding.v1.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/IanStuardo-Dev/backend-crud/internal/infrastructure/embedding/grpcpb;grpcpb'
  _globals['_EMBEDREQUEST']._serialized_start=52
  _globals['_EMBEDREQUEST']._serialized_end=80
  _globals['_EMBEDRESPONSE']._serialized_start=82
  _globals['_EMBEDRESPONSE']._serialized_end=176
  _globals['_EMBEDDINGSERVICE']._serialized_start=178
  _globals['_EMBEDDINGSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
