package seeds

func seedGroceryProducts() []seedProduct {
	return []seedProduct{
		groceryProduct("SEED-GRC-001", "Arroz Grano Largo Gallo 1kg", "Arroz blanco de grano largo para acompanamientos y preparaciones diarias.", "pantry", "Gallo", 1890, 40),
		groceryProduct("SEED-GRC-002", "Arroz Integral CampoLindo 1kg", "Arroz integral de coccion tradicional rico en fibra.", "pantry", "CampoLindo", 2290, 28),
		groceryProduct("SEED-GRC-003", "Arroz Jasmine Oriente 1kg", "Arroz jazmin aromatico ideal para platos orientales y salteados.", "pantry", "Oriente", 2890, 18),
		groceryProduct("SEED-GRC-004", "Fideos Spaghetti Durum 400g", "Spaghetti de trigo durum para salsas rojas y preparaciones familiares.", "pantry", "Pastabella", 990, 52),
		groceryProduct("SEED-GRC-005", "Fideos Tallarin Casero 400g", "Tallarin largo de textura suave para preparaciones caseras.", "pantry", "Pastabella", 990, 47),
		groceryProduct("SEED-GRC-006", "Fideos Espirales Tricolor 400g", "Pasta espiral tricolor para ensaladas y platos frios.", "pantry", "Pastabella", 1190, 31),
		groceryProduct("SEED-GRC-007", "Harina Todo Uso Molino 1kg", "Harina blanca multiuso para panqueques, masas y reposteria.", "baking", "Molino Sur", 1490, 36),
		groceryProduct("SEED-GRC-008", "Harina Integral Molino 1kg", "Harina integral de trigo para panificacion y recetas saludables.", "baking", "Molino Sur", 1690, 26),
		groceryProduct("SEED-GRC-009", "Avena Tradicional Andina 1kg", "Avena tradicional en hojuelas para desayunos y granolas caseras.", "breakfast", "Andina", 2590, 25),
		groceryProduct("SEED-GRC-010", "Avena Instantanea Canela 400g", "Avena instantanea sabor canela para desayuno rapido.", "breakfast", "Andina", 1790, 20),
		groceryProduct("SEED-GRC-011", "Lentejas Seleccionadas 1kg", "Lentejas de coccion uniforme para guisos y ensaladas.", "legumes", "CampoFertil", 1990, 34),
		groceryProduct("SEED-GRC-012", "Lentejas Rojas Express 500g", "Lentejas rojas de coccion rapida para sopas y pure.", "legumes", "CampoFertil", 2090, 18),
		groceryProduct("SEED-GRC-013", "Porotos Negros Familia 1kg", "Porotos negros tradicionales para recetas caseras y bowls.", "legumes", "La Familia", 2290, 24),
		groceryProduct("SEED-GRC-014", "Porotos Granados Tradicion 1kg", "Porotos granados secos para preparaciones chilenas tradicionales.", "legumes", "La Familia", 2390, 19),
		groceryProduct("SEED-GRC-015", "Garbanzos Premium 1kg", "Garbanzos grandes seleccionados para hummus y guisos.", "legumes", "CampoFertil", 2490, 23),
		groceryProduct("SEED-GRC-016", "Garbanzos Cocidos Lata 400g", "Garbanzos cocidos listos para usar en ensaladas y salteados.", "legumes", "ListoYa", 1390, 17),
		groceryProduct("SEED-GRC-017", "Quinoa Blanca Andina 500g", "Quinoa blanca lavada para ensaladas, bowls y acompanamientos.", "pantry", "Andina", 3190, 14),
		groceryProduct("SEED-GRC-018", "Chia Semillas Naturales 250g", "Semillas de chia para yogur, batidos y reposteria.", "breakfast", "Vida Natural", 2690, 12),
		groceryProduct("SEED-GRC-019", "Linaza Molida 250g", "Linaza molida lista para agregar a jugos y mezclas saludables.", "breakfast", "Vida Natural", 1990, 13),
		groceryProduct("SEED-GRC-020", "Maiz Para Palomitas 500g", "Maiz de grano entero para preparar cabritas en casa.", "snacks", "CampoLindo", 1290, 22),
		groceryProduct("SEED-GRC-021", "Aceite Maravilla Dorado 1L", "Aceite vegetal de maravilla para frituras y cocina diaria.", "condiments", "Dorado", 2490, 33),
		groceryProduct("SEED-GRC-022", "Aceite Canola Light 1L", "Aceite de canola suave para ensaladas y coccion ligera.", "condiments", "Dorado", 2990, 21),
		groceryProduct("SEED-GRC-023", "Aceite Oliva Suave 500ml", "Aceite de oliva suave para salteados y aderezos.", "condiments", "Olivia", 4990, 16),
		groceryProduct("SEED-GRC-024", "Vinagre Manzana Natural 500ml", "Vinagre de manzana para aderezos y conservas.", "condiments", "Olivia", 1490, 14),
		groceryProduct("SEED-GRC-025", "Vinagre Blanco Cocina 1L", "Vinagre blanco clasico para cocina y preparaciones caseras.", "condiments", "Olivia", 1390, 20),
		groceryProduct("SEED-GRC-026", "Salsa Soya Clasica 150ml", "Salsa de soya tradicional para marinados y salteados.", "condiments", "Oriente", 1590, 18),
		groceryProduct("SEED-GRC-027", "Salsa Inglesa Tradicional 150ml", "Salsa inglesa de sabor intenso para carnes y salsas.", "condiments", "Oriente", 1690, 15),
		groceryProduct("SEED-GRC-028", "Ketchup Receta Casera 500g", "Ketchup tradicional de tomate para acompanar comidas.", "condiments", "Sabor Hogar", 1890, 26),
		groceryProduct("SEED-GRC-029", "Mostaza Suave 250g", "Mostaza suave para sandwiches y aderezos.", "condiments", "Sabor Hogar", 1290, 21),
		groceryProduct("SEED-GRC-030", "Mayonesa Clasica 500g", "Mayonesa clasica cremosa para ensaladas y sandwiches.", "condiments", "Sabor Hogar", 2290, 24),
		groceryProduct("SEED-GRC-031", "Salsa Tomate Basilico 400g", "Salsa de tomate con albahaca para pastas y pizza.", "canned-goods", "La Huerta", 1490, 18),
		groceryProduct("SEED-GRC-032", "Pure Tomate Tradicional 210g", "Pure de tomate concentrado para guisos y salsas.", "canned-goods", "La Huerta", 790, 27),
		groceryProduct("SEED-GRC-033", "Pasta Tomate Concentrada 180g", "Pasta de tomate para realzar sabor y color en preparaciones.", "canned-goods", "La Huerta", 990, 19),
		groceryProduct("SEED-GRC-034", "Tomates Pelados Lata 400g", "Tomates pelados enteros listos para cocinar.", "canned-goods", "La Huerta", 1390, 16),
		groceryProduct("SEED-GRC-035", "Salsa Bolognesa Lista 350g", "Salsa boloñesa lista para servir con pasta.", "canned-goods", "La Huerta", 1890, 14),
		groceryProduct("SEED-GRC-036", "Atun Lomitos Agua 160g", "Atun en lomitos al agua para ensaladas y sandwiches.", "canned-goods", "Mar Azul", 1590, 29),
		groceryProduct("SEED-GRC-037", "Atun Lomitos Aceite 160g", "Atun en lomitos con aceite vegetal de sabor tradicional.", "canned-goods", "Mar Azul", 1690, 24),
		groceryProduct("SEED-GRC-038", "Sardinas Tomate 155g", "Sardinas en salsa de tomate para consumo directo o acompanar arroz.", "canned-goods", "Mar Azul", 1190, 15),
		groceryProduct("SEED-GRC-039", "Jurel Natural Lata 425g", "Jurel natural en lata para ensaladas, tortillas y guisos.", "canned-goods", "Mar Azul", 1790, 17),
		groceryProduct("SEED-GRC-040", "Caballa Aceite Oliva 120g", "Caballa en aceite de oliva de sabor intenso.", "canned-goods", "Mar Azul", 1890, 10),
		groceryProduct("SEED-GRC-041", "Choclo Dulce Lata 340g", "Choclo dulce en granos listo para ensaladas y acompanamientos.", "canned-goods", "ListoYa", 1190, 18),
		groceryProduct("SEED-GRC-042", "Arvejas Lata 340g", "Arvejas verdes en conserva para guarniciones y ensaladas.", "canned-goods", "ListoYa", 1090, 17),
		groceryProduct("SEED-GRC-043", "Porotos Verdes Conserva 340g", "Porotos verdes en conserva listos para calentar y servir.", "canned-goods", "ListoYa", 1290, 12),
		groceryProduct("SEED-GRC-044", "Duraznos Mitades Almibar 820g", "Duraznos en almibar para postres y reposteria.", "canned-goods", "DulceCampo", 2190, 14),
		groceryProduct("SEED-GRC-045", "Coctel Frutas Almibar 820g", "Coctel de frutas en almibar para ensaladas y postres.", "canned-goods", "DulceCampo", 2290, 11),
		groceryProduct("SEED-GRC-046", "Caldo Gallina 12 Cubos", "Caldo concentrado sabor gallina para sopas y arroces.", "pantry", "Sabor Hogar", 990, 28),
		groceryProduct("SEED-GRC-047", "Caldo Carne 12 Cubos", "Caldo concentrado sabor carne para guisos y salsas.", "pantry", "Sabor Hogar", 990, 26),
		groceryProduct("SEED-GRC-048", "Sal Fina Marina 1kg", "Sal fina marina para cocina de uso diario.", "pantry", "Marina", 790, 34),
		groceryProduct("SEED-GRC-049", "Sal Rosada Gourmet 500g", "Sal rosada granulada para terminaciones y cocina especial.", "pantry", "Marina", 1590, 12),
		groceryProduct("SEED-GRC-050", "Azucar Blanca Refinada 1kg", "Azucar blanca refinada para bebidas y reposteria.", "sweeteners", "DulceVida", 1290, 37),
		groceryProduct("SEED-GRC-051", "Azucar Rubia Natural 1kg", "Azucar rubia para preparaciones caseras y horneados.", "sweeteners", "DulceVida", 1490, 22),
		groceryProduct("SEED-GRC-052", "Endulzante Sucralosa 100ml", "Endulzante liquido con sucralosa para bebidas calientes y frias.", "sweeteners", "DulceVida", 1990, 16),
		groceryProduct("SEED-GRC-053", "Miel Abeja Multifloral 500g", "Miel multifloral natural para endulzar infusiones y desayunos.", "sweeteners", "Vida Natural", 3990, 13),
		groceryProduct("SEED-GRC-054", "Mermelada Frutilla Casera 350g", "Mermelada de frutilla estilo casero para panes y tostadas.", "breakfast", "DulceCampo", 1790, 18),
		groceryProduct("SEED-GRC-055", "Mermelada Damasco Tradicional 350g", "Mermelada de damasco de textura suave para desayunos.", "breakfast", "DulceCampo", 1790, 16),
		groceryProduct("SEED-GRC-056", "Cereal Maiz Clasico 500g", "Cereal de maiz crocante para desayuno familiar.", "breakfast", "Morning", 2890, 19),
		groceryProduct("SEED-GRC-057", "Granola Miel Almendras 400g", "Granola con miel y almendras para yogur y bowls.", "breakfast", "Morning", 3290, 15),
		groceryProduct("SEED-GRC-058", "Choco Cereal Kids 400g", "Cereal sabor chocolate orientado a desayuno infantil.", "breakfast", "Morning", 2990, 14),
		groceryProduct("SEED-GRC-059", "Leche Polvo Entera 800g", "Leche en polvo entera de uso familiar.", "dairy", "CampoLeche", 6290, 17),
		groceryProduct("SEED-GRC-060", "Leche Condensada 397g", "Leche condensada para reposteria y postres.", "dairy", "CampoLeche", 1890, 20),
		groceryProduct("SEED-GRC-061", "Manjar Tradicional 400g", "Manjar tradicional cremoso para postres y pan.", "dairy", "CampoLeche", 1790, 21),
		groceryProduct("SEED-GRC-062", "Cacao Polvo Reposteria 250g", "Cacao en polvo para postres, queques y chocolate caliente.", "baking", "ChocoCasa", 2490, 12),
		groceryProduct("SEED-GRC-063", "Chocolate Tableta Leche 100g", "Chocolate de leche en tableta para consumo directo o reposteria.", "snacks", "ChocoCasa", 1490, 25),
		groceryProduct("SEED-GRC-064", "Cafe Capuccino Vainilla 200g", "Preparado instantaneo tipo capuccino sabor vainilla.", "hot-beverages", "Dolca", 3990, 18),
		groceryProduct("SEED-GRC-065", "Te Negro Clasico 100 Bolsitas", "Te negro tradicional en formato familiar.", "hot-beverages", "TeaHouse", 2790, 20),
		groceryProduct("SEED-GRC-066", "Te Verde Menta 20 Bolsitas", "Infusion de te verde con hojas de menta.", "hot-beverages", "TeaHouse", 1590, 14),
		groceryProduct("SEED-GRC-067", "Te Manzanilla 20 Bolsitas", "Infusion de manzanilla en bolsitas para consumo diario.", "hot-beverages", "TeaHouse", 1490, 16),
		groceryProduct("SEED-GRC-068", "Yerba Mate Tradicional 500g", "Yerba mate tradicional para preparaciones calientes.", "hot-beverages", "MateSur", 3690, 11),
		groceryProduct("SEED-GRC-069", "Chocolate Instantaneo Familiar 400g", "Chocolate instantaneo para leche caliente o fria.", "hot-beverages", "ChocoCasa", 2990, 15),
		groceryProduct("SEED-GRC-070", "Cafe Descafeinado Suave 170g", "Cafe soluble descafeinado de sabor suave en frasco.", "hot-beverages", "Nestle", 7190, 12),
		groceryProduct("SEED-GRC-071", "Galletas Soda Clasicas 180g", "Galletas soda clasicas para colaciones y aperitivos.", "biscuits", "SnackTime", 1090, 24),
		groceryProduct("SEED-GRC-072", "Galletas Crackers Salvado 180g", "Galletas crackers con salvado para picoteo y desayuno.", "biscuits", "SnackTime", 1190, 17),
		groceryProduct("SEED-GRC-073", "Galletas Vainilla Rellenas 126g", "Galletas rellenas sabor vainilla para colacion.", "biscuits", "SnackTime", 990, 22),
		groceryProduct("SEED-GRC-074", "Galletas Chocolate Rellenas 126g", "Galletas rellenas sabor chocolate para colacion.", "biscuits", "SnackTime", 990, 23),
		groceryProduct("SEED-GRC-075", "Galletas Avena Pasas 180g", "Galletas de avena con pasas para snack dulce.", "biscuits", "SnackTime", 1390, 16),
		groceryProduct("SEED-GRC-076", "Bizcochos Dulces Tradicionales 200g", "Bizcochos dulces crujientes para acompanar te o cafe.", "biscuits", "SnackTime", 1490, 14),
		groceryProduct("SEED-GRC-077", "Tostadas Integrales 270g", "Tostadas integrales crujientes para desayuno y onces.", "biscuits", "Morning", 1690, 19),
		groceryProduct("SEED-GRC-078", "Tostadas Clasicas 270g", "Tostadas clasicas para acompanar mantequilla y mermelada.", "biscuits", "Morning", 1590, 18),
		groceryProduct("SEED-GRC-079", "Barras Cereal Miel 6 Unidades", "Barras de cereal con miel para colaciones rapidas.", "snacks", "Morning", 1890, 15),
		groceryProduct("SEED-GRC-080", "Barras Cereal Chocolate 6 Unidades", "Barras de cereal sabor chocolate para colaciones.", "snacks", "Morning", 1890, 16),
		groceryProduct("SEED-GRC-081", "Mani Tostado Salado 250g", "Mani tostado con sal para aperitivos y picoteos.", "snacks", "Crunch", 1490, 20),
		groceryProduct("SEED-GRC-082", "Mani Japones 200g", "Mani japones crocante para snack salado.", "snacks", "Crunch", 1590, 18),
		groceryProduct("SEED-GRC-083", "Mix Frutos Secos 200g", "Mezcla de nueces, almendras y pasas para snack saludable.", "snacks", "Vida Natural", 3490, 12),
		groceryProduct("SEED-GRC-084", "Almendras Naturales 200g", "Almendras naturales sin sal para colaciones y reposteria.", "snacks", "Vida Natural", 3790, 11),
		groceryProduct("SEED-GRC-085", "Nueces Mariposa 200g", "Nueces mariposa seleccionadas para snack y cocina.", "snacks", "Vida Natural", 3990, 10),
		groceryProduct("SEED-GRC-086", "Pasas Rubias 250g", "Pasas rubias para reposteria, ensaladas y colaciones.", "snacks", "Vida Natural", 1790, 14),
		groceryProduct("SEED-GRC-087", "Ciruelas Secas 250g", "Ciruelas secas descarozadas para snack o cocina.", "snacks", "Vida Natural", 1990, 13),
		groceryProduct("SEED-GRC-088", "Papas Chips Sal Marina 150g", "Papas fritas laminadas con sal marina.", "snacks", "Crunch", 1890, 21),
		groceryProduct("SEED-GRC-089", "Papas Chips Queso 150g", "Papas chips sabor queso para picoteos y reuniones.", "snacks", "Crunch", 1990, 20),
		groceryProduct("SEED-GRC-090", "Ramitas Queso 150g", "Snack horneado sabor queso tipo ramitas.", "snacks", "Crunch", 1690, 17),
		groceryProduct("SEED-GRC-091", "Harina Maiz Precocida 1kg", "Harina de maiz precocida para arepas y masas.", "baking", "Maizoro", 2290, 15),
		groceryProduct("SEED-GRC-092", "Polenta Instantanea 500g", "Polenta instantanea para acompanamientos y recetas caseras.", "pantry", "Maizoro", 1490, 16),
		groceryProduct("SEED-GRC-093", "Cous Cous Tradicional 500g", "Cous cous de coccion rapida para ensaladas y acompanamientos.", "pantry", "Oriente", 1990, 14),
		groceryProduct("SEED-GRC-094", "Pure Papas Instantaneo 125g", "Pure de papas instantaneo para preparacion rapida.", "pantry", "Sabor Hogar", 1290, 19),
		groceryProduct("SEED-GRC-095", "Sopa Instantanea Pollo Fideos 65g", "Sopa instantanea sabor pollo con fideos en porcion individual.", "pantry", "Sabor Hogar", 690, 26),
		groceryProduct("SEED-GRC-096", "Sopa Instantanea Verduras 65g", "Sopa instantanea sabor verduras en porcion individual.", "pantry", "Sabor Hogar", 690, 24),
		groceryProduct("SEED-GRC-097", "Gelatina Frutilla 100g", "Preparado para gelatina sabor frutilla.", "desserts", "DulceCampo", 790, 22),
		groceryProduct("SEED-GRC-098", "Gelatina Naranja 100g", "Preparado para gelatina sabor naranja.", "desserts", "DulceCampo", 790, 21),
		groceryProduct("SEED-GRC-099", "Flan Vainilla 120g", "Preparado para flan sabor vainilla.", "desserts", "DulceCampo", 990, 18),
		groceryProduct("SEED-GRC-100", "Levadura Instantanea Pan 125g", "Levadura instantanea para masas, pizzas y pan casero.", "baking", "Molino Sur", 1490, 13),
	}
}

func groceryProduct(sku, name, description, category, brand string, priceCents int64, stock int) seedProduct {
	return seedProduct{
		CompanyID:   1,
		BranchID:    1,
		SKU:         sku,
		Name:        name,
		Description: description,
		Category:    category,
		Brand:       brand,
		PriceCents:  priceCents,
		Currency:    "CLP",
		Stock:       stock,
	}
}
